[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "nickmarks"
dynamic = ["version"]
description = "cross-platform bookmark manager"
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "Nick Talbert", email = "nickjamestalbert@gmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "sqlalchemy",
  "notion-client",
  "dotenv",
]

[project.urls]
Documentation = "https://github.com/Nick Talbert/nickmarks#readme"
Issues = "https://github.com/Nick Talbert/nickmarks/issues"
Source = "https://github.com/Nick Talbert/nickmarks"

[tool.hatch.version]
path = "src/nickmarks/__about__.py"

[tool.hatch.envs.default]
dependencies = [
  "ipython",
]
[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/nickmarks tests}"

[tool.coverage.run]
source_pkgs = ["nickmarks", "tests"]
branch = true
parallel = true
omit = [
  "src/nickmarks/__about__.py",
]

[tool.coverage.paths]
nickmarks = ["src/nickmarks", "*/nickmarks/src/nickmarks"]
tests = ["tests", "*/nickmarks/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
